<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Terms and condition , Privacy Policies</title>
    <link rel="stylesheet" href="tc.css">
</head>
<body>
    <h1>David's Grill</h1>

    <h2>Terms & Condition and Privacy Policy</h2>
    <h3> GENERAL TERMS </h3>
    <p>By accessing and placing an order and making a reservation in David's Grill, you confirm that you are in agreement with and bound by the terms of services contained in the Terms & Condition outlined below: These terms apply to the entire website and any email or other type of communication between you and David's Grill</p>
    <p>Under no circumstances shall David's Grill team be liable for any direct, indirect, special, incidental, or consequential damages including, but not limited to, loss of data or profit, arising out of the use, or the inability to use, the materials on the site, even if David's Grill team or an authorized representative has been advised of the possibility of such damages, If your use of materials from the site results in the need for servicing, repair or correction of equipment or data, you assume any costs thereof.</p>
    <p>David's Grill will not be responsible for any outcome that may occur during the usage of our resources. We reserve the right to change prices and revise the resources usage policy at any moment.</p>

    <br>
    <h3>LICENSE</h3>
    <p>David's Grill grants you a revocable, non-exclusive, non-transferable, limited license to download, install and use the website strictly by the terms of this Agreement. These Terms & Conditions are a contract between you and David's Grill. ("we", "our" or "us") grants you revocable, non-exclusive, non-transferable, limited license to download, install and use the website strictly by the terms of this Agreement.</p>

    <br>
    <h3>DEFINITION AND KEY TERMS </h3>
    <header>For this Terms & Condition
    </header>
    <p>•	<b>Cookie:</b> small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</p>
    <p>•	<b>Company:</b> when this policy mentions "Company", "we", "us", or "our", it refers to David's Grill, Brgy. Sambat Balayan, Batangas that is responsible for your information under this Privacy Policy</p>
    <p>•	<b>Country:</b> Where David's grill or the owners/founders of David's Grill are based, in this case in the Philippines.</p>
    <p>•	<b>Customer:</b> Refers to the company, organization, or person that signs up to use David's grill Service to manage their relationships with your customers or service users.</p>
    <p>•	<b>Device:</b> Any internet-connected device such as a phone, tablet, computer, or any other device that can be used to visit David's grill and use the services.</p>
    <p>•	<b>IP address:</b> Every device connected to the Internet is assigned a number known as an Internet protocol (IP)address. These numbers are usually assigned in geographic blocks. an IP address can often be used to identify the location from which a device is connecting to the Internet.</p>
    <p>•	<b>Personnel:</b> Refers to those individuals who are employed by David's Grill or are under contract to perform a service on behalf of one of the parties</p>
    <p>•	<b>Personal Data:</b> Any information that directly, indirectly, or in connection with other information including a personal identification number allows for the identification or identifiability of a natural person.</p>
    <p>•	<b>Service:</b> refers to the service provided by David's Grill as described in the relative terms (if available) and on this platform</p>
    <p>•	<b>Third-party service:</b> Refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.</p>
    <p>•	<b>Website:</b> David's Grill site which can be accessed via this URL: davidsgrill.com</p>
    <p>•	<b>You:</b> a person or entity that is registered with David's Grill to use the Services.</p>
    
    <br>
    <h3>RESTRICTIONS</h3>
    <p> •	You agree not to, and you will not permit others to:</p>
    <p> •	License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose, or otherwise commercially exploit the service of making the platform available to any third party. </p>
    <p> •	Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the service.</p>
    <p> •	Remove, alter or obscure any proprietary notice9including ay notice of copyright or trademark) of or its affiliates, partners, suppliers, or the licensors of the service.</p>

    <br>
    <h3>WELCOME TO DAVID’S GRILL</h3>
    <p>•	Customer must book a reservation for at least one to three (1-3) days before the desired date and for the walk-in customers, the restaurant will gladly accept them if there is an available table for them.</p>
    <p>•	David’s Grills offers reservation and ordering online but there are only selected places where that offer is suited.</p>
    <p>•	Customer who made a reservation is obligate to make a 50% down payment for whatever he or she is reserving.</p>
    <p>•	Customer from other provinces must provide a health declaration form from their municipality/ barangay upon arrival or even just their vaccination card.</p>
    <p>•	Customer coming from Batangas Province shall provide Valid I.D showing their residence upon arrival and their vaccination card.</p>
    <p>•	Confirmed order with the list of customers with:
        <p>------ o	 Name</p>
        <p>------ o	 Address</p>
        <p>------ o  Contact Number</p>
    </p>
    <p>•	Confirmed reservation with a list of customers with:
        <p>------ o	 Name</p>
        <p>------ o	 Address</p>
        <p>------ o  Contact Number</p>
    </p>
    <p>•	Upon Arrival of Customers for each customer provided by the restaurant must be accomplished.
        <p>------ o  Temperature check</p>
        <p>------ o  Facemask, No entry</p>
        <p>------ o  The restaurant must not accommodate beyond curfew hours</p>
        <p>------ o  Presentation of Health Declaration Form or Residence ID or Vaccination Card</p>
     </p>

     <br>
     <h3>ABOUT THE RESTAURANT SYSTEM</h3>
     <p>•  The Website or the system is open from 9 am to 9 pm</p>
     <p>•  The Unregistered customer is unable to make any transaction on the website, but they can view the website homepage.</p>
     <p>•  Upon creating an account on the website, the customer is asked to submit 3 pictures back-to-back pictures of their ID and them along with their ID this is to secure that there will be no scamming or using of other people’s identity.</p>
     <p>•  The user account is manually checked and verified by the admin /manager and it takes 2-5 mins on verifying their customer account.</p>
     <p>•  The customer can input their remarks or request and reminder if there are any ingredients that they would not like to include or they had allergies with that is in that particular dish. The request will also be submitted along with the orders and reservations that they make.</p>
     <p>•  When booking a reservation, the customer also needed to fill up a health declaration form that will be presented by the system, so that when they arrived at the restaurant their body temperature will only be taken.</p>

     <br>
     <h3>RESTAURANT POLICY</h3>
     <p>1. Smoking is strictly prohibited.</p>
     <p>2. The customer shall observe and heed all safety precautions and warning signs issued by the management within the resort premises.</p>
     <p>3. The restaurants and their crews, and employees shall not be held liable for any injury, damages, or loss incurred by any person because of the consumption of the food and/or drinks brought into the resort, or resort food and/or drinks brought out of the premises without prior arrangement.</p>
     <p>4. The customer is requested to use the restaurant’s utensils and facilities with proper care. Any damage caused due to the fault or negligence of the guests shall be charged to their account.</p>
     <p>5.  The restaurant has parking spaces allotted for its guests. Drivers of the vehicles must present their driver’s license or any other form of government ID with security upon entry at the parking area of the resort. The resort assumes no liability for any loss and/or damages to the vehicles parked therein and to the valuables left inside the vehicles.</p>
     <p>6. Restaurant customers are obliged to make an effort to keep the surroundings clean. Guests should refrain from throwing rubbish anywhere other than the strategically located trash bins.</p>
     <p>7. Tricycles and other public motor vehicles which may transport guests to and from the resort are not in any way affiliated with the Restaurants. The resto shall not be liable for any loss, damage, or injury caused by or on the occasion of their use</p>
     <p>8. Restaurant customers are expected to behave in a manner not disruptive to the peace of the Restaurant and of the stay of another customer. The restaurant management reserves the right to ask misbehaving customer/s to leave the premises of the Restaurant.</p>
     <p>9. Bringing in fireworks, firearms, and other deadly weapons into the restaurant is strictly prohibited and violators will be dealt with accordingly.</p>

     <br>
     <h3>COVID PROTOCOLS</h3>
     <h4>Covid restrictions and safety protocols</h4>
     <p>A. Guests must complete a Health Declaration Form or present a vaccination card upon check-in.</p>
     <p>B. Body temperature checking using a thermal scanner at the resort entrances shall be undertaken for all guests by a qualified health or medical staff or trained hotel personnel. Only guests cleared during screening shall be allowed to enter the hotel perimeter to check in. Those with fever and flu-like symptoms will not be allowed to enter the establishment and will be referred to the doctor on duty, to the nearest hospital, or the Barangay Health Emergency Response Team (BHERT) by the DOH prescribed protocol.</p>
     <p>C. Guests shall be advised to disinfect their shoes using sanitizing mats provided at the entrances.</p>
     <p>D. Physical Distancing measures, hand hygiene, and respiratory etiquette must be observed when handling guests at the check-in counter.</p>
     <p>E. Guests must be informed of the management policies on room occupancy, dining, and use of public areas imposed to ensure safety and reduce the risk of infection. Physical distancing, wearing of face mask, proper handwashing/hand sanitizing practice must be emphasized.</p>
     <p>F. No showing of guests around the room after check-in. Guest escorting to the room may be allowed following the strict observance of physical distancing and in compliance with the health and safety protocols set by the DOH.</p>
     <p>G. Only single up to double room occupancy is allowed. Couples or family members who share the same household may be allowed in double or twin occupancy rooms. A distance of 1 to 2 meters between the beds is highly encouraged.</p>
     <p>H. During the stay, guests must strictly follow the following:</p>
     <p>------ 1. wear facemask when roaming around and if needed;</p>
     <p>------ 2. Proper disposal of used facemask;</p>
     <p>------ 3. Mingling with occupants of other rooms are not encouraged;</p>
     <p>------ 4. Practice proper handwashing etiquette/hand hygiene, respiratory etiquette, and proper use of facemask; and</p>
     <p>------ 5. Strict observance of Physical Distancing</p>

     <br>
     <h3>RESERVATION</h3>
     <p>•	To successfully make a reservation the customer will be asked to pay a down payment</p>
     <p>•	The table reservation fee will be based on the number of customers that will arrive. The minimum number of persons per table reservation is 1 person while the maximum is 15 persons. The reservation fee per 11 persons will be 70 pesos.</p>
     <p>•	GCash payment is the payment method that will be used by the customer to pay their reservation fee</p>
     <p>•	The customer will be reminded of their table reservation twice through text message by restaurant management. The first one is 15 mins before the reserved time of the customer and the second will be at the exact time of the reservation.</p>
     <p>•	The restaurant will give them 2-3 minutes allotted time to the customer, if the customer did not show on the given allotted time the reserved table will be canceled by the management and allow their walk-in customer to use that table.</p>
    
     <br>
     <h3>REFUND FOR RESERVATION</h3>
     <p>• In reservation there will be no refund</p>

     <br>
     <h3>RETURN AND REFUND</h3>
     <p>Thanks for ordering with us. we appreciate the fact that you like to buy the foods we serve and offer. We also want to make sure you have a rewarding experience while you're exploring, evaluating, and purchasing our products.</p>
     <p>As with any shopping experience, some terms and conditions apply to the transactions at our company. we'll be as brief as our attorneys will allow. The main thing to remember is that by placing an order or making a purchase from us, you agree to the terms along with our Privacy Policy.</p>
     <p>If, for any reason. You are not completely satisfied with any good or service that we provide, don't hesitate to contact us and we will discuss any of the issues you are going through with our product.</p>

     <br>
     <h3>CANCELLATION</h3>
     <p>•	Cancel button will be disabled after 5 mins of submitting an order.</p>
     <p>•	Cancel button for reservation will be disabled after 5 days they reserve.</p>

     <br>
     <h3>ORDERS</h3>
     <p>•	If the order reaches 300 pesos, the customer needs to pay a partial payment.</p>
     <p>•	The customer can edit the sender's and receiver information in my profile module.</p>
     <p>•	The customer can monitor their order if it is pending, canceled, processing, on delivery, and delivered.</p>

     <br>
     <h3>VOUCHER</h3>
     <p>•	There is a 5% discount and can be availed once they reach the 1000 pesos amount of their orders. it will be applied to the delivery fee.</p>
    
     <br>
     <h3>PAYMENT</h3>
     <p>•	There are two (2) payment methods. The GCash and COD.</p>
     <p>•	If the customer exceeds the maximum amount of the orders the customer will be asked to pay half of it and their payment method will be automatically GCash.</p>
     <p>•	It takes 2 - 3 minutes for the order confirmation</p>
     <p>If the default address of the customer changed wherein the one that will be receiving the order is not the same as the one who order the food, the payment method of the customer will automatically GCash</p>

     <br>
     <h3>DELIVERY</h3>
     <p>The customer should input their exact location thru a map for the delivery fee;</p>
     <p>------ Brgy. Sambat Balayan to Calaca = 17.3 km  = 150 pesos</p>
     <p>------ Brgy. Sambat Balayan to Tuy = 11.8 km = 100 pesos</p>
     <p>------ Brgy. Sambat Balayan to Nasugbu = 25.5 km = 170 pesos</p>
     <p>------ Brgy. Sambat Balayan to Lian= 15.7 km = 120 pesos</p>
     <p>------ Brgy. Sambat Balayan to Calatagan = 17.3 km = 150 pesos</p>
     <p>------ Brgy. Sambat Balayan to Balibago = 5.8 km = 70 pesos</p>
     <p>------ Brgy. Sambat Balayan to Brgy. Navotas = 4.8 km = 70 pesos</p>
     <p>------ Brgy. Sambat Balayan to Brgy. Caloocan = 2.8  km = 50 pesos</p>
     <p>------ Brgy. Sambat Balayan to Brgy. Santol = 2.5 km = 50 pesos</p>
     <p>------ Brgy. Sambat Balayan to Brgy. San Piro = 6.3 km = 70 pesos</p>
     <p>------ Brgy. Sambat Balayan to Brgy. Duhatan = 2.5 km = 50 pesos</p>
     <p>------ Brgy. Sambat Balayan to Brgy. Taludtod = 10.2 km = 90 pesos</p>
     <p>------ Brgy. Sambat Balayan to Brgy. Dalig = 2.7 km = 50 pesos</p>
     <p>------ Brgy. Sambat Balayan to Brgy. 1 = 6.2 km = 70 pesos</p>
     <p>------ Brgy. Sambat Balayan to Brgy. 2 = 3.1 km = 50 pesos</p>
     <p>------ Brgy. Sambat Balayan to Brgy. Calan = 12.3 km = 100 pesos </p>
     <p>------ Brgy. Sambat Balayan to Brgy. Sampaga = 7.8 km = 80 pesos</p>
     <p>------ Brgy. Sambat Balayan to Brgy. Baclaran = 8.0 km = 85 pesos</p>
     <p>------ Brgy. Sambat Balayan to Brgy. Carenahan = 7.6 kmn = 80 pesos</p>
     <p>------ Brgy. Sambat Balayan to Brgy. Lanatan = 3.9 km = 50 pesos</p>
     <p>------ Brgy. Sambat Balayan to Brgy. Malalay = 4.1 km = 50 pesos</p>
     <p>------ Brgy. Sambat Balayan to Brgy. Dilao = 5.3 km = 70 pesos</p>
     <p>------ Brgy. Sambat Balayan to Brgy. Gumamela = 3.8 km = 50 pesos</p>
     <p>------ Brgy. Sambat Balayan to Brgy. Pook = 6.7 km = 70 pesos</p>
     <p>------ Brgy. Sambat Balayan to Brgy. Palikpikan = 3.6 km = 50 pesos</p>
     <p>------ Brgy. Sambat Balayan to Brgy. Tanggoy = 4.1 km = 60 pesos</p>
     <p>------ Brgy. Sambat Balayan to Brgy. Cayponce = 4.8 km = 70 pesos</p>
     <p>------ Brgy. Sambat Balayan to Brgy. Magabe = 6.6 km = 70 pesos</p>
     <p>------ Brgy. Sambat Balayan to Brgy. Munting Tubig = 4.4 km = 70 pesos</p>
     <p>------ Brgy. Sambat Balayan to Brgy. San Juan = 4.8 km = 70 pesos</p>
     <p>------ Brgy. Sambat Balayan to Brgy. Calzada = 2.3 km = 50 pesos</p>
     <p>------ Brgy. Sambat Balayan to Brgy. Canda = 1.7 km = 50 pesos</p>
     <p>------ Brgy. Sambat Balayan to Brgy. Dao = 5.8 km = 70 pesos</p>
     <p>------ Brgy. Sambat Balayan to Brgy. Gimalas = 5.6 km = 60 pesos</p>
     <p>------ Brgy. Sambat Balayan to Putol Street = 3.4 km =  50 pesos</p>

     <br>
     <h3>YOUR SUGGESTION</h3>
     <p>Any, feedback, comments, idea, improvements, or suggestions (collectively, "Suggestions") provided by you to us concerning the service shall remain our sole and exclusive property. we shall be free to use, copy modify, publish, or redistribute the Suggestion for any purpose and in any way without any credit or any compensation to you.</p>

     <br>
     <h3>YOUR CONSENT</h3>
     <p> We've updated our Terms & Conditions to provide you with complete transparency into what is being set when you visit our site and how it's being used. By using our service, registering an account, or making a purchase, you hereby consent to our Terms & conditions
    </p>

    <br>
    <h3>CHANGES TO OUR TERMS & CONDITIONS</h3>
    <p>You acknowledge and agree that we may stop (permanently or temporarily) providing the Service (or any features within the Service) to you or users generally at our sole discretion, without prior notice to you. You may stop using the Service at any time. You do not need to specifically inform us when you stop using the Service. You acknowledge and agree that if we disable access to your account, you may be prevented from accessing the Service, your account details, or any files other materials which are contained in your account. if we devise to change our Term & Condition, we will post those changes on this page, and/or update the Terms & Condition modification date below.</p>

    <br>
    <h3>CONSEQUENCES OF NON-COMPLIANCE  </h3>
    <p>If you fail to comply with the Terms and Conditions, without prior notice and any liability to you or any other person, we reserve the right to take all or any of the following actions:</p>
    <p>Cancellation or modification of your reservation(s) or transaction(s);</p>
    <p>Issuance of a warning to you;</p>
    <p>Termination, restriction, or suspension of your use of or access to any or all part of the Website;</p>
    <p>Commencement of legal action against you; or</p>
    <p>Disclosure of information about you to law enforcement authorities as we may determine in our sole discretion.</p>
    <p>The above is not exhaustive. We may take any other action at our absolute discretion. </p>

    <br>
    <h3>INDEMNIFICATION</h3>
    <p>You agree to indemnify and hold us and our parents, subsidiaries, affiliates, officers, employees, agents, partners, and licensors (if any) harmless from any claim or demand, including reasonable attorneys' fees, due to or arising out of your: (a) use of the service; (b) violation of this Agreement or any law or regulation; or (c) violation of any right of a third party.</p>

    <br>
    <h3>COPYRIGHT INFRINGEMENT NOTICE</h3>
    <p>If you are a copyright owner or such owner's agent and believe any material from us constitutes an infringement on your copyright, please contact us setting forth the following information: (a) a physical or electronic signature of the copyright owner or a person authorized to act on his behalf; (b) identification of the material that is claimed to be infringing; (C) your contact information, including your address, telephone number, and an email; (d) a statement by you that you have a good faith belief that use of the material is not authorized by the copyright owners, and (e) the statement that the information in the notification is accurate, and, under penalty of perjury you are authorized to act on bel of the owner.</p>

    <br>
    <h3>MODIFICATIONS TO OUR SERVICE</h3>
    <p>We reserve the right to modify, suspend or discontinue, temporarily or permanently, the service or any service to which it connects, with or without notice and without liability to you</p>

    <br>
    <h3>UPDATES TO OUR SERVICE </h3>
    <p>We may from time to time provide enhancements or improvements to the features/ functionality of the service, which may include patches, bug fixes, updated, upgrades, and other modifications ("Updates"). Updates may modify or delete certain features and/or functionalities of the service. You agree that we have no obligation to (i) provide any Updates, or (ii) continue to provide or enable any particular features and/or functionalities of the service to you. You further agree that all updates will be (i) deemed to constitute an integral part of the service, and (i) subject to the terms and conditions of this Agreement.</p>

    <br>
    <h3>TERM AND TERMINATION</h3>
    <p>This agreement shall remain in effect until terminated by you or us. We may, in its sole discretion, at any time and for no reason, suspend or terminate this Agreement with or without prior notice. This Agreement will terminate immediately, without prior notice from us, if you fail to comply with any provision of this Agreement. You may also terminate this Agreement by deleting the service and all copies thereof from your computer. Upon termination of this Agreement, you shall cease all use of the service and delete all copies of the service from your computer. Termination of this Agreement will not limit any of our rights or remedies at law or inequality in case of breach by you (during the term of this Agreement) of any of your obligations under the present Agreement.</p>
    <p>If you are a copyright owner or such owner's agent and believe any material from us constitutes an infringement on your copyright, please contact us setting forth the following information: (a) a physical or electronic signature of the copyright owner or a person authorized to act on his behalf; (b) identification of the material that is claimed to be infringing; (c) your contact information, including your address, telephone number, and an email; (d) a statement by you that you have a good faith belief that use of the material is not authorized by the copyright owners; and (e) the statement that the information in the notification is accurate and under penalty of perjury you are authorized to act on behalf of the owner.</p>

    <br>
    <h3>SUBMISSIONS AND PRIVACY</h3>
    <p>If you submit or post any ideas, creative suggestions, design, photographs, information, advertisements, data, or proposals, including ideas for new or improved products, services, features, technologies, or promotions, you expressly agree that such submissions will automatically be treated as non-confidential and non-proprietary and will become the sole property of us without any compensation or credit to you whatsoever. We and our affiliates shall have no obligations concerning such submissions or posts and may use the ideas contained in such submissions or posts for any purposes in any medium in perpetuity, including, but not limited to, developing manufacturing, and marketing products and services using such ideas.</p>

    <br>
    <h3>PROMOTIONS</h3>
    <p>We may, from time to time, include contests, promotions, sweepstakes, or other activities ("Promotions") that require you to submit material or information concerning yourself. Please note that all Promotions may be governed by separate rules that may contain certain eligibility requirements, such as restrictions as to age and geographic location. You are responsible for areas all Promotions rules to determine whether or not you are eligible to participate. If you enter any Promotion, you agree to abide by and comply with all Promotions Rules. Additional terms and conditions may apply to the purchase of goods or services on or through the Services, which terms and conditions are made a part of this Agreement by this reference.</p>

    <br>
    <h3>TYPOGRAPHICAL ERRORS</h3>
    <p>in the event a product and/or service is listed at an incorrect price or with incorrect information due to typographical error, we shall have the right to refuse or cancel any orders placed for the product and/or service listed at the incorrect price. We shall have the right to refuse or cancel any such order whether or not the order has been confirmed and your credit card charged. If your credit card has already been charged for the purchase and your order is canceled, we shall immediately issue a credit to your credit card account or another payment account in the amount of the charge.</p>

    <br>
    <h3>PRIVACY POLICY/POLICY AGREEMENT</h3>
    <p>David’s Grill ("we," "our", or "us") is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by David's Grill.</p>
    <p>This Privacy policy applies to our website, davidsgrill.com, and its associated subdomains (collectively, our "Service"). By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy policy and our Terms of Service.</p>

    <br>
    <h3>WHAT INFORMATION DO WE COLLECT?</h3>
    <p>We collect information from you when you visit our service, register, place an order, subscribe to our newsletter, respond to a survey or fill out a form</p>
    <p>-Name/Username</p>
    <p>-Phone Numbers</p>
    <p>-Email Address</p>
    <p>-Billing Address</p>
    <p>-Age</p>
    <p>-Password</p>
    <p>ID Picture</p>

    <br>
    <h3>HOW DO WE USE THE INFORMATION WE COLLECT?</h3>
    <p>Any of the information we collect from you may be used in one of the following ways:</p>
    <p>-To personalize your experience (your information helps us to better respond to your individual needs)</p>
    <p>-To improve our service (we continually strive to improve our service offering based on the information and feedback we receive from you)</p>
    <p>-To improve customer service (your information helps us to more effectively respond to your customer service request and support needs)</p>
    <p>-To process the transaction </p>
    <p>-To administer a contest, promotion, survey, or other site feature</p>
    <p>-To send periodic emails</p>

    <br>
    <h3>WHEN DO WE USE CUSTOMER INFORMATION FROM THIRD PARTIES?</h3>
    <p>We received some information from the third parties when you contact us. For example, when you submit your email address to us to show interest in becoming our customer, we received information from a third party that provides automated fraud detection services to us. We also occasionally collect information that is made publicly available on social media websites. You can control how much of your information social media websites make public by visiting these websites and changing your privacy settings.</p>

    <br>
    <h3>DO WE SHARE THE INFORMATION WE COLLECT WITH THIRD PARTIES?</h3>
    <p>We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you. we may also share it with our current and future affiliated companies and business partners, and if we are involved in a merger, asset sale, or other business reorganization, we may also share or transfer your personal and non-personal information to our successors-in-interest</p>
    <p>We may engage trusted third-party service providers to perform functions and provide services to us, such as hosting and maintaining our server and our service, database storage, and management, e-mail management, storage marketing, credit card processing, customer service, and fulfilling orders for products and services you may purchase through our service. We will likely share your personal information, and possibly some non-personal information, with these third parties to enable them to perform these services for us and you.</p>
    <p>We may share portions of our log file data, including IP address, for analytics purposes with third parties such as web analytics partners, application developers, and ad networks. if your IP address is shared, it may be used to estimate general location and other technographic such as connection speed, whether you have visited the service in a shared location, and type of device used to visit the service. They may aggregate information about our advertising and what you see on the service and then provide auditing, researching, and reporting for us and our advertiser</p>
    <p>We may also disclose personal and non-personal information about you to the government or law enforcement officials or private parties as we, in our sole discretion, believe necessary or appropriate to respond to claims, legal process (including subpoenas), to protect our rights and interests or those of a third party, the safety of the public or any person, to prevent or stop any illegal, unethical or legally actionable activity, or to otherwise comply with an applicable court order, laws rules and regulations.</p>

    <br>
    <h3>WHERE AND WHEN IS INFORMATION COLLECTED FROM CUSTOMERS AND END-USERS?</h3>
    <p>We will collect the personal information that you submit to us. We may also receive personal information about you from third parties as described above.</p>

    <br><h3>HOW DO WE USE YOUR EMAIL ADDRESS?</h3>
    <p>By submitting your email address to our service, you agree to receive emails from us. You can cancel your participation in any of these email lists at any time by clicking on the opt-out link or other unsubscribe option that is included in the respective email. We only send emails to people who have authorized us to contact them, either directly, or through a third party. We do not send unsolicited commercial emails, because we hate spam as much as you do. By submitting your email address, you also agree to allow us to use your email address for customer audience targeting on sites like Facebook, where we display custom advertising to specific people who have opted-in to receive communications from us. The email address submitted only through the order processing page will be used for the sole purpose of sending your information and updates about your order. If, however, you have provided the same email to us through another method, we may use it for any of the purposes stated in this Policy. Note: If at any time you would like to unsubscribe from receiving future emails, we include detailed unsubscribe instructions at the bottom of each email.</p>

    <br>
    <h3>COULD MY INFORMATION BE TRANSFERRED TO OTHER COUNTRIES?</h3>
    <p>We are incorporated in the Philippines. Information collected via our website, through direct interaction with you, or from the use of our help services may be transferred from time to time to our offices or personnel, or third parties, located throughout the world, and maybe viewed and hosted anywhere in the world, including countries that may not have laws of general applicability regulating the use and transfer of such data. To the fullest extent allowed by applicable law, by using any of the above, you voluntarily consent to the transborder transfer and hosting of such information.</p>

    <br>
    <h3>IS THE INFORMATION COLLECTED THROUGH OUR SERVICE SECURE?</h3>
    <p>We take precautions to protect the security of your information. We have physical, electronic, and managerial procedures to help safeguard, prevent unauthorized access, maintain data security, and correctly use your information. However, neither people nor security systems are foolproof, including encryption systems. In addition, people can commit intentional crimes, make mistakes or fail to follow policies. Therefore, while we use reasonable efforts to protect your personal information, we cannot guarantee its absolute security. if applicable law  imposes any non-disclaimed duty to protect your personal information, you agree that intentional misconduct will be the standards used to measure our compliance with that duty</p>

    <br>
    <h3>CAN I UPDATE OR CORRECT MY INFORMATION?</h3>
    <p>The rights you to request updates or corrections to the information we collect depend on your relationship with us. Personnel may update or correct their information as detailed in our internal company employment policies. Customers have the right to request the restriction of certain uses and disclosures of personally identifiable information as follows. You can contact us to (1) update or correct your personally identifiable information (2) change your preferences concerning communications and other information you receive from us, (3) delete the personally identifiable information maintained about you on our system (subject to the following paragraph), by canceling your account. Such updates, corrections, changes, and deletions will not affect other information that we maintain or information that we have provided to third parties by this Privacy Policy before such update, correction, change, or deletion. To protect your privacy and security, we may take reasonable steps (such as requesting a unique password) to verify your identity before granting you profile access or making corrections. You are responsible for maintaining the secrecy of your unique password and account information at all times. You should be aware that it is not technologically possible to remove every record of the information you have provided to us from our system. The need to back up our systems to protect information from inadvertent loss means that a copy of your information may exist in a non-erasable form that will be difficult or impossible for us to locate. Promptly after receiving your request, all the personal information stored in databases we actively use, and other readily searchable media will be updated, corrected, changed, or deleted, as appropriate, as soon as and to the extent reasonably and technically practicable. If you are an end and wish to update, delete, or receive any information we have about you, you may do so by contacting the organization of which you are a customer.</p>

    <br>
    <h3>PERSONNEL</h3>
    <p>If you are of our workers or applicants, we collect the information you voluntarily provide to us. We use the information collected for Human Resources purposes to administer benefits to workers and screen applicants. You may contact us to (1) update or correct your information (2) change your preferences concerning communications and other information you receive from us, or (3) receive a record of the information we have relating to you. Such updates, corrections, changes, and deletions will not affect other information that we maintain, or information that we provided to third parties by this Privacy Policy before such update, collection, change, or deletion</p>

    <br>
    <h3>SALE OF BUSINESS</h3>
    <p>We reserve the right to transfer information to a third party in the event of a sale, merger, or other transfer of all or substantially all of the assets of us or any of its Corporate Affiliates (as defined herein), or that portion of us or any of its Corporate Affiliates to which the Service relates, or if we discontinue our business or file a petition or have filed against us a petition in bankruptcy, reorganization or similar proceeding, provided that the third party agrees to adhere to the terms of this Privacy Policy</p>

    <br>
    <h3>AFFILIATES</h3>
    <p>We may disclose information (including personal information) about you to our Corporate Affiliates. For purposes of this Privacy Policy, "Corporates Affiliate" means any person or entity which directly or indirectly controls, is controlled by or is under common control with us, whether by ownership or otherwise. Any information relating to you provided to our Corporate Affiliates will be treated by those Corporate Affiliates by the terms of this Privacy policy.</p>

    <br><h3>HOW LONG DO WE KEEP YOUR INFORMATION?</h3>
    <p>We keep your information only so long as we need it to provide service to you and fulfill the purposes described in this policy. This is also the case for anyone that we share your information with and who carries out service on our behalf. When we no longer need to use your information and there is no need for us to keep it to comply with legal or regulatory obligations, we'll either remove it from our systems or depersonalize it so that we can't identify you.</p>

    <br>
    <h3>HOW DO WE PROTECT YOUR INFORMATION?</h3>
    <p>We implement a variety of security measures to maintain the safety of your personal information when you place an order or enter submit, or access your personal information. We offer the use of a secure server. all supplied sensitive/credit information is transmitted via Secure Socket Layer (SSL) technology and then encrypted into our Payment gateway providers database only to be accessible by those authorized with special access rights to such systems, and are required to keep the information confidential. After a transaction, your private information (credit cards, social security numbers, financial, etc) is never kept on file. We cannot, however, ensure or warrant the absolute security of any information you transmit to us or guarantee that your information on the Service may not be accessed, disclosed, altered, or destroyed by a breach of any of our physical, technical, or managerial safeguards.</p>

    <br>
    <h3>GOVERNING LAW</h3>
    <p>The laws of the Philippines, excluding its conflicts of law rules, shall govern this Agreement and your use of our service. your use of our service may also be subject to other local, state, national, or international laws.</p>

    <br>
    <h3>YOUR CONSENT</h3>
    <p>By using our service, registering an account, or making a purchase, you consent to this Privacy Policy.</p>

    <br>
    <h3>COOKIES</h3>
    <p>We use "cookies" to identify the areas of our website that you have visited. A cookie is a small piece of data stored on your computer or mobile device by your web browser. we use cookies to enhance the performance and function of our service but are non-essential to their use. However, without these cookies, certain functionally like videos may become unavailable or you would be required to enter your login details every time you visit our platform as we would not be able to remember that you had logged in previously. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally Identifiable Information in Cookies.</p>
    <p>We use cookies to enhance the performance and functionality of our service but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit our service as we would not be able to remember that you had logged in previously.</p>

    <br>
    <h3>PAYMENT DETAILS</h3>
    <p>In respect to any credit card or other payment processing details you have provided us, we commit that this confidential information will be stored in the most secure manner possible.</p>

    <br>
    <h3>CHANGES TO OUR PRIVACY PRIVACY</h3>
    <p>If we decide to change our privacy policy, we will post those changes on this page, and/or update the Privacy Policy modification date below.</p>

    <br>
    <h3>THIRD-PARTY SERVICES</h3>
    <p>We may display, include or make available third-party content (including data, information, application, and other products services) or provide links to third-party websites or services ("Third-Party Services").</p>
    <p>You acknowledge and agree that we shall not be responsible for any Third-Party Services, including their accuracy, completeness, timelessness, validity, copyright compliance, legality, decency, quality, or any other aspect thereof. We do not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services.</p>
    <p>Third-Party Services and links thereto are provided solely as a convenience to your access and use them entirely at your own risk and subject to such third parties terms and conditions.</p>

    <br>
    <h3>TRACKING TECHNOLOGIES</h3>
    <p>-Google Maps APIs</p>
    <p>Google Maps API is a robust tool that can be used to create a custom map, a searchable map, check-in functions, display live data syncing with location, plan routes, or create a mashup just to name a few</p>
    <p>Google Map API may collect information that is held by its Privacy Policy</p>

    <br>
    <h3>WHAT IS PERSONAL DATA?</h3>
    <p>Any data that relates or an identifiable or identified individual. GDPR covers a broad spectrum of information that could be used on its own, or in combination with other pieces of information, to identify a person. Personal data extends beyond a person's name or email address. Some examples include financial information, political opinions, genetic data, biometric data, IP addresses, physical addresses, sexual orientation, and ethnicity. The Data Protection Principles include requirements such as:</p>
    <p>--- •	Personal data collected must be processed in a fair, legal, and transparent way and should only be used in a way that a person would reasonably expect.</p>
    <p>--- •	Personal data should only be collected to fulfill a specific purpose and it should only be used for that purpose. Organizations must specify why they need personal data when they collect it.</p>
    <p>--- •	Personal data should be held no longer than necessary to fulfill its purpose.</p>
    <p>--- •	People covered by the GDPR have the right to access their data. They can also request a copy of their data, and that their data be updated, deleted, restricted, or moved to another organization.</p>

    <br>
    <h3>INDIVIDUAL DATA SUBJECT'S RIGHTS-DATA ACCESS, PORTABILITY, AND DELETION</h3>
    <p>We are committed to helping our customers meet the data subject rights requirements of GDPR. processes or stores all personal data in fully vetted, DPA compliant vendors. We do store all conversation and personal data for up to 6 years unless your account is deleted. In which case, we dispose of all data by our Terms of Service and Privacy Policy, but we will not hold it longer than 60 days.</p>
    <p>We are aware that if you are working with EU customers, you need to be able to provide them with the ability to access, update, retrieve and remove personal data. We got you! We've been set up as self-service from the start and have always given you access to your data and your customer’s data. Our customer support team is here for you to answer any questions you might have about working with API</p>
    
    <br>
    <h3>THIRD-PARTY SERVICE</h3>
    <p>We may display, include or make available third-party content (including data, information, applications, and other product service0 or provide links to third-party or services ("Third-Party Service"). You acknowledge and agree that we shall not be responsible for any Third-Party service, including their accuracy, completeness, validity, copyright compliance, legality, decency, quality, or any other aspect thereof. We do not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Servicer. Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties terms and conditions.</p>

    <br>
    <h3>DISCLAIMERS  </h3>
    <p>All reasonable efforts have been made to ensure the accuracy of the content and materials displayed on the Website. We regularly review the Website and, where appropriate, will update pages to reflect any changes to the features, functionality, and available services of this Website.</p>
    <p>The Website, the content and materials, and goods and services on the Website are provided "as is" and on an "as available" basis without warranties of any kind, and we disclaim all warranties, whether express or implied, to the maximum extent permitted by law, including but not limited to warranties of title, merchantability, fitness for purpose, non-infringement of intellectual property or proprietary rights, confidentiality or privacy of any communication or information transmitted on the Website or any sites linked to the Website, compatibility between the Website and any software or hardware, accuracy, reliability or availability of the goods and services on offer, or arising from course of dealing or usage of trade. You accept all risk and responsibility for your use of the Website, including the submission of any personal information.</p>

    <br>
    <h3>LIMITATION OF LIABILITY</h3>
    <p>Notwithstanding any damage that you might incur, the entire liability of us and any of our suppliers under any provision of this Agreement and your exclusive remedy for all of the foregoing shall be limited to the amount paid by you for the service. To the maximum extent permitted by applicable law, in no event shall we or our supplies be liable for any special, incidental, indirect, or consequential damages whatsoever (including, but not limited to, damages for loss of profits, for lost data, or other information, for business interruption, for personal injury, for loss of privacy arising out of or in any way related to the use of or inability to use the service, third-party software and/or third-party hardware used with the service, or in any way related to the use of or inability to use the Agreement), even if we or any suppliers has been advised of the possibility of such damages and even if the remedy fails of its essential purpose. Some states/jurisdictions do not allow the exclusion or limitation of incidental or consequential damages, so the above limitation or exclusion may not.</p>

    <br><h3>CONTACT US</h3>
    <p>Don't hesitate to contact us if you have any question</p>
    <p>-Via Email: davidsgrillrestosy2021@gmail.com</p>
    <p>-Via Phone Number: 09975242698</p>
    <p>-Via this Link: davidsgrill.com</p>
    <p>-Via this Address: Brgy. Sambat Balayan, Batangas</p>

</body>
</html>